#!/usr/bin/env python3
"""
Verify the integration of Jax's notes and narrative evidence into both affidavits.
"""
import re
from pathlib import Path

def verify_affidavit(file_path, prefix):
    """Verify an integrated affidavit"""
    with open(file_path, 'r') as f:
        content = f.read()
    
    # Count responses
    responses = re.findall(rf'\*\*{prefix} ([\d.]+)\*\*', content)
    
    # Check for placeholder citations
    generic_placeholders = re.findall(rf'\[Annexure {prefix}-X\]', content)
    specific_citations = re.findall(rf'\[Annexure {prefix}-([\d.]+)\]', content)
    
    # Check for problematic language
    hyperbolic = re.findall(r'\b(absolutely|completely|totally|utterly|entirely|massive|huge|enormous|catastrophic|devastating)\b', content, re.IGNORECASE)
    speculative = re.findall(r'\b(may|might|could|possibly|potentially|probably|likely|appears to|seems to|suggests that)\b', content, re.IGNORECASE)
    subjective = re.findall(r'\b(I believe|I think|in my opinion)\b', content, re.IGNORECASE)
    
    return {
        'total_responses': len(responses),
        'generic_placeholders': len(generic_placeholders),
        'specific_citations': len(specific_citations),
        'hyperbolic': len(hyperbolic),
        'speculative': len(speculative),
        'subjective': len(subjective)
    }

def main():
    base_path = Path('/home/ubuntu/canima/affidavits_refined')
    
    jax_v14 = base_path / 'Jacqueline_Answering_Affidavit_v14_INTEGRATED.md'
    dan_v14 = base_path / 'Daniel_Answering_Affidavit_v14_INTEGRATED.md'
    
    jax_stats = verify_affidavit(jax_v14, 'JR')
    dan_stats = verify_affidavit(dan_v14, 'DR')
    
    # Generate report
    report_file = Path('/home/ubuntu/canima/INTEGRATION_VERIFICATION_REPORT.md')
    with open(report_file, 'w') as f:
        f.write("# Integration Verification Report\n\n")
        f.write("**Date:** 2 November 2025\n")
        f.write("**Generated by:** verify_integration.py\n\n")
        f.write("---\n\n")
        
        f.write("## 1. Coverage Verification\n\n")
        
        f.write("### 1.1 Jacqueline's Affidavit (v14 - Integrated)\n\n")
        f.write(f"- **Total responses:** {jax_stats['total_responses']}\n")
        f.write(f"- **Generic placeholders:** {jax_stats['generic_placeholders']}\n")
        f.write(f"- **Specific citations:** {jax_stats['specific_citations']}\n\n")
        
        f.write("### 1.2 Daniel's Affidavit (v14 - Integrated)\n\n")
        f.write(f"- **Total responses:** {dan_stats['total_responses']}\n")
        f.write(f"- **Generic placeholders:** {dan_stats['generic_placeholders']}\n")
        f.write(f"- **Specific citations:** {dan_stats['specific_citations']}\n\n")
        
        f.write("---\n\n")
        f.write("## 2. Language Quality Verification\n\n")
        
        f.write("### 2.1 Jacqueline's Affidavit (v14)\n\n")
        if jax_stats['hyperbolic'] > 0:
            f.write(f"- ⚠️ Hyperbolic language: {jax_stats['hyperbolic']} instances\n")
        else:
            f.write("- ✓ No hyperbolic language\n")
        
        if jax_stats['speculative'] > 0:
            f.write(f"- ⚠️ Speculative language: {jax_stats['speculative']} instances\n")
        else:
            f.write("- ✓ No speculative language\n")
        
        if jax_stats['subjective'] > 0:
            f.write(f"- ⚠️ Subjective language: {jax_stats['subjective']} instances\n")
        else:
            f.write("- ✓ No subjective language\n")
        f.write("\n")
        
        f.write("### 2.2 Daniel's Affidavit (v14)\n\n")
        if dan_stats['hyperbolic'] > 0:
            f.write(f"- ⚠️ Hyperbolic language: {dan_stats['hyperbolic']} instances\n")
        else:
            f.write("- ✓ No hyperbolic language\n")
        
        if dan_stats['speculative'] > 0:
            f.write(f"- ⚠️ Speculative language: {dan_stats['speculative']} instances\n")
        else:
            f.write("- ✓ No speculative language\n")
        
        if dan_stats['subjective'] > 0:
            f.write(f"- ⚠️ Subjective language: {dan_stats['subjective']} instances\n")
        else:
            f.write("- ✓ No subjective language\n")
        f.write("\n")
        
        f.write("---\n\n")
        f.write("## 3. Integration Summary\n\n")
        
        f.write("| Metric | Jacqueline (v14) | Daniel (v14) | Status |\n")
        f.write("|:-------|:-----------------|:-------------|:-------|\n")
        f.write(f"| **Total Responses** | {jax_stats['total_responses']} | {dan_stats['total_responses']} | ✓ |\n")
        f.write(f"| **Generic Placeholders** | {jax_stats['generic_placeholders']} | {dan_stats['generic_placeholders']} | {'✓' if jax_stats['generic_placeholders'] == 0 and dan_stats['generic_placeholders'] == 0 else '⚠️'} |\n")
        f.write(f"| **Specific Citations** | {jax_stats['specific_citations']} | {dan_stats['specific_citations']} | ✓ |\n")
        f.write(f"| **Language Quality** | {'✓' if jax_stats['hyperbolic'] == 0 and jax_stats['speculative'] == 0 and jax_stats['subjective'] == 0 else '⚠️'} | {'✓' if dan_stats['hyperbolic'] == 0 and dan_stats['speculative'] == 0 and dan_stats['subjective'] == 0 else '⚠️'} | {'✓' if (jax_stats['hyperbolic'] + jax_stats['speculative'] + jax_stats['subjective'] + dan_stats['hyperbolic'] + dan_stats['speculative'] + dan_stats['subjective']) == 0 else '⚠️'} |\n")
        
        f.write("\n---\n\n")
        f.write("## 4. Next Steps\n\n")
        f.write("- Replace specific citation placeholders with actual annexure descriptions\n")
        f.write("- Add legal citations for all arguments (Companies Act, Trust Property Control Act)\n")
        f.write("- Review complementary narrative structure for coherence\n")
        f.write("- Ensure evidence-based approach throughout\n")
    
    print(f"Verification report generated: {report_file}")
    print(f"\nJacqueline's Affidavit (v14):")
    print(f"  Responses: {jax_stats['total_responses']}")
    print(f"  Generic placeholders: {jax_stats['generic_placeholders']}")
    print(f"  Specific citations: {jax_stats['specific_citations']}")
    print(f"  Language issues: {jax_stats['hyperbolic'] + jax_stats['speculative'] + jax_stats['subjective']}")
    
    print(f"\nDaniel's Affidavit (v14):")
    print(f"  Responses: {dan_stats['total_responses']}")
    print(f"  Generic placeholders: {dan_stats['generic_placeholders']}")
    print(f"  Specific citations: {dan_stats['specific_citations']}")
    print(f"  Language issues: {dan_stats['hyperbolic'] + dan_stats['speculative'] + dan_stats['subjective']}")

if __name__ == '__main__':
    main()

